Gradient Descent and Cost function

In [75]:
import numpy as np

In [76]:
def gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 1000
    n = len(x)
    learning_rate = 0.08
    for i in range(iterations):
        y_predicted = m_curr * x + b_curr 
        md = -(2/n) * sum (x * (y - y_predicted))
        bd = -(2/n) * sum (y - y_predicted)
        m_curr = m_curr - learning_rate * md 
        b_curr = b_curr - learning_rate * bd
        print ("m {}, b {}, iteration {}".format(m_curr, b_curr, i))

In [77]:
x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])

In [78]:
gradient_descent(x, y)

m 4.96, b 1.44, iteration 0
m 0.4991999999999983, b 0.26879999999999993, iteration 1
m 4.451584000000002, b 1.426176000000001, iteration 2
m 0.892231679999997, b 0.5012275199999995, iteration 3
m 4.041314713600002, b 1.432759910400001, iteration 4
m 1.2008760606719973, b 0.7036872622079998, iteration 5
m 3.7095643080294423, b 1.4546767911321612, iteration 6
m 1.4424862661541864, b 0.881337636696883, iteration 7
m 3.4406683721083144, b 1.4879302070713722, iteration 8
m 1.6308855378034224, b 1.0383405553279617, iteration 9
m 3.2221235247119777, b 1.5293810083298451, iteration 10
m 1.7770832372205707, b 1.1780607551353204, iteration 11
m 3.0439475772474127, b 1.5765710804477953, iteration 12
m 1.8898457226770244, b 1.3032248704973899, iteration 13
m 2.898169312926714, b 1.6275829443328358, iteration 14
m 1.9761515088959358, b 1.4160484030347593, iteration 15
m 2.7784216197824048, b 1.6809279342791488, iteration 16
m 2.0415541605113807, b 1.5183370872989306, iteration 17
m 2.67961703610786

Dummy Variables and One Hot Encoding

In [79]:
import pandas as pd
df = pd.read_csv("../../SPL/Datasets/Untitled 1.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [80]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [81]:
merged = pd.concat([df, dummies], axis = 'columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [82]:
final = merged.drop(['town', 'west windsor'], axis = 'columns')
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [83]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [84]:
X = final.drop('price', axis = 'columns')
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [85]:
Y = final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [86]:
model.fit(X, Y)

LinearRegression()

In [87]:
model.predict(X)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [88]:
model.score(X, Y)

0.9573929037221873

In [89]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [90]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [99]:
X = dfle[['town', 'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [100]:
Y = dfle.price.values
Y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [93]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [97]:
X = ct.fit_transform(X)
X = X[:,1:]
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [98]:
model.fit(X,Y)

LinearRegression()